### PR TITLE
Add sponsors styling.

### PR DESCRIPTION
**Pull request by addict3d**
Add the layout/styling for sponsorship cards at the different tiers.

Consider the design rough and the implementation more like the prototype. Suggestions/critique/feedback very welcome on this.

### CODE REVIEW

**Comment by thilobillerbeck** [comment]
image

Just quckly put this together. This has still al lot of room for improvement, but maybe you can give me some feedback.

(Is there a possibility, that we could give sponsors a title? That would take away the need to fill the image background with the tier color)

**Comment by thilobillerbeck** [comment]
image

This would be an alternative approach, which is much more lighter on the color side.

**Comment by addict3d** [comment]
> (Is there a possibility, that we could give sponsors a title? That would take away the need to fill the image background with the tier color)

In that case, would each sponsor's title indicate their tier? each card could look something like this
```
Company A
Platinum sponsor
{ Company A Logo Image }
{ Company A description }
```

**Comment by addict3d** [comment]
> image
> 
> This would be an alternative approach, which is much more lighter on the color side.

IMO this looks nicer.

**Comment by addict3d** [comment]
One thing I noticed which seems wrong (in my current implementation), is that images with different aspect ratios will be constrained by width.

Given that the sponsor images can be any kind of rectangle, some may be a square, and some are wider rectangles, what are your thoughts on that? Should they be laid out so that the images are resized to be all the same height?

**Comment by thilobillerbeck** [comment]
I think we should constraint the height and only force a specific width if needed.

**Pull request merged**
